version: 2.1

jobs:
  first_job:
    docker:
      - image: circleci/openjdk:8-jdk  # お使いの環境に合わせてDockerイメージを指定してください
    steps:
      - run:
          name: Create directory and file
          command: mkdir -p workspace && touch workspace/file.txt

  second_job:
    docker:
      - image: circleci/openjdk:8-jdk  # お使いの環境に合わせてDockerイメージを指定してください
    steps:
      - checkout
      - run:
          name: Check file existence
          command: ls workspace/file.txt

workflows:
  version: 2
  build_and_test:
    jobs:
      - first_job
      - second_job:
          requires:
            - first_job

