version: 2.1

jobs:
  create-file:
    working_directory: "/home/circleci/tmp"
    docker:
      - image: cimg/base:current
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "create file"
          command: |
            mkdir -p workspace && touch workspace/file.txt
            ls /home/circleci/tmp/workspace/file.txt
      - persist_to_workspace:
          root: /home/circleci/tmp/workspace
          paths:
            - file.txt

  ls-file:
    working_directory: "/home/circleci/tmp"
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/tmp/workspace
      - run:
          name: "ls file"
          command: "ls /home/circleci/tmp/workspace/file.txt"

workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - create-file
      - ls-file:
          requires:
            - create-file

